#!/bin/bash
set -eo pipefail

docker compose \
  -f ./main.yml \
  -f ./node-1.yml \
  -f ./node-2.yml \
  -f ./gateway.yml \
  --env-file ./main.env \
  -p "xmtp-network" \
  down \
  --remove-orphans

echo "✅ XMTP Network stopped"
