#!/bin/bash
set -euo pipefail

# Initialization.
script_dir=$(dirname "$(realpath "$0")")
repo_root=$(realpath "${script_dir}/../")
cd "${repo_root}"

# Configuration.

# Blockchain and environment.
export ADMIN_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
export XMTPD_APP_CHAIN_RPC_URL="http://localhost:8545"
export XMTPD_APP_CHAIN_WSS_URL="ws://localhost:8545"
export XMTPD_SETTLEMENT_CHAIN_RPC_URL="http://localhost:8545"
export XMTPD_SETTLEMENT_CHAIN_WSS_URL="ws://localhost:8545"
export XMTPD_CONTRACTS_CONFIG_FILE_PATH="../xmtpd-debugging/environments/anvil.json"

cd "$HOME/projects/xmtp/xmtpd/"

go run -ldflags="-X main.Version=$(git describe HEAD --tags --long)" cmd/xmtpd-cli/main.go \
    --config-file=$XMTPD_CONTRACTS_CONFIG_FILE_PATH \
    --app-rpc-url=$XMTPD_APP_CHAIN_RPC_URL \
    --settlement-rpc-url=$XMTPD_SETTLEMENT_CHAIN_RPC_URL \
    --log-level=debug \
    --private-key="$ADMIN_KEY" \
"$@"
